In [2]:
import numpy as np

### Cвойства транспонированных матриц

#### Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [10]:
A = np.matrix('3 1 7; 8 9 10')
print(" Изначальная матрица\n",A)
R = (A.T).T
print("\nДважды транспортированная матрица\n", R)

 Изначальная матрица
 [[ 3  1  7]
 [ 8  9 10]]

Дважды транспортированная матрица
 [[ 3  1  7]
 [ 8  9 10]]


#### Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [11]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
L = (A + B).T
R = A.T + B.T
print("Транспортированная сумма матриц\n", L)
print("\nСумма транспортированных матриц\n", R)

Транспортированная сумма матриц
 [[ 7  4  4]
 [10 12  5]
 [ 8 11  9]]

Сумма транспортированных матриц
 [[ 7  4  4]
 [10 12  5]
 [ 8 11  9]]


#### Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [12]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print("Транспортирование произведения матриц\n", L)
print("\nПроизведение транспортированных матриц в обратном порядке\n", R)

Транспортирование произведения матриц
 [[15 34 13]
 [41 85 31]
 [37 89 35]]

Произведение транспортированных матриц в обратном порядке
 [[15 34 13]
 [41 85 31]
 [37 89 35]]


#### Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [13]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
k = 5
L = (k * A).T
R = k * (A.T)
print("Транспортирование произведения матрицы на число\n", L)
print("\nПроизведение числа на транспортированную матрицу\n", R)

Транспортирование произведения матрицы на число
 [[15 20  5]
 [10 25 10]
 [ 5 30 15]]

Произведение числа на транспортированную матрицу
 [[15 20  5]
 [10 25 10]
 [ 5 30 15]]


#### Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [29]:
B = np.matrix('3 2 1; 4 5 1; 2 3 4')
B_det = np.linalg.det(B)
B_T_det = np.linalg.det(B.T)
print("Определитель исходной матрицы:", format(B_det, '.9g'))
print("\nОпределитель транспортированной матрицы:", format(B_T_det, '.9g'))

Определитель исходной матрицы: 25

Определитель транспортированной матрицы: 25


 ### Cвойства операции умножения матрицы 

#### Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [31]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
L = 1 * A
R = A
print("Исходная матрица\n", A)
print("\nПроизведение матрицы на единицу\n", L)

Исходная матрица
 [[3 2 1]
 [4 5 6]
 [1 2 3]]

Произведение матрицы на единицу
 [[3 2 1]
 [4 5 6]
 [1 2 3]]


#### Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [32]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
Z = np.matrix('0 0 0; 0 0 0; 0 0 0')
L = 0 * A
print("Нулевая равная размерностью исходной матрица\n", Z)
print("\nПроизведение матрицы на ноль\n", L)

Нулевая равная размерностью исходной матрица
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Произведение матрицы на ноль
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [34]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
p = 5
q = 4
L = (p + q) * A
R = p * A + q * A
print("Произведение матрицы на сумму чисел\n", L)
print("\nСумма произведний матрицы на числа\n", R)

Произведение матрицы на сумму чисел
 [[27 18  9]
 [36 45 54]
 [ 9 18 27]]

Сумма произведний матрицы на числа
 [[27 18  9]
 [36 45 54]
 [ 9 18 27]]


#### Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [35]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
p = 5
q = 4
L = (p * q) * A
R = p * (q * A)
print("Произведение матрицы на произведение чисел\n", L)
print("\nПроизведение второго числа и заданной матрицы, умноженное на первое число\n", R)

Произведение матрицы на произведение чисел
 [[ 60  40  20]
 [ 80 100 120]
 [ 20  40  60]]

Произведение второго числа и заданной матрицы, умноженное на первое число
 [[ 60  40  20]
 [ 80 100 120]
 [ 20  40  60]]


#### Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [36]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
k = 4
L = k * (A + B)
R = k * A + k * B
print("Произведение суммы матриц на число\n", L)
print("\nСумма произведений матриц на число\n", R)

Произведение суммы матриц на число
 [[28 40 32]
 [16 48 44]
 [16 20 36]]

Сумма произведений матриц на число
 [[28 40 32]
 [16 48 44]
 [16 20 36]]


### Свойства сложения матриц

#### Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [37]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
L = A + B
R = B + A
print("Сумма матриц A + B\n", L)
print("\nСумма матриц B + A\n", R)

Сумма матриц A + B
 [[ 7 10  8]
 [ 4 12 11]
 [ 4  5  9]]

Сумма матриц B + A
 [[ 7 10  8]
 [ 4 12 11]
 [ 4  5  9]]


#### Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [2]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
C = np.matrix('5 4 3; 3 5 7; 9 2 5')
L = A + (B + C)
R = (A + B) + C
print("Сумма матриц A + (B + C)\n", L)
print("\nСумма матриц (A + B) + C\n", R)

Сумма матриц A + (B + C)
 [[12 14 11]
 [ 7 17 18]
 [13  7 14]]

Сумма матриц (A + B) + C
 [[12 14 11]
 [ 7 17 18]
 [13  7 14]]


#### Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей :

In [3]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
L = A + (-1)*A
print(L)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Свойства произведения матриц

#### Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [4]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
C = np.matrix('5 4 3; 3 5 7; 9 2 5')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print("Произведение матриц A * (B * C)\n", L)
print("\nПроизведение матриц (A * B) * C\n", R)

Произведение матриц A * (B * C)
 [[ 531  339  517]
 [1226  739 1142]
 [ 473  277  431]]

Произведение матриц (A * B) * C
 [[ 531  339  517]
 [1226  739 1142]
 [ 473  277  431]]


#### Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [5]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
C = np.matrix('5 4 3; 3 5 7; 9 2 5')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print("Произведение матрицы на сумму матриц\n", L)
print("\nСумма произведений матриц\n", R)

Произведение матрицы на сумму матриц
 [[ 45  65  65]
 [123 138 166]
 [ 51  51  67]]

Сумма произведений матриц
 [[ 45  65  65]
 [123 138 166]
 [ 51  51  67]]


#### Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [6]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
B = np.matrix('4 8 7; 0 7 5; 3 3 6')
L = A.dot(B)
R = B.dot(A)
print("Произведение матриц A * B\n", L)
print("\nПроизведение матриц B * A\n", R)

Произведение матриц A * B
 [[15 41 37]
 [34 85 89]
 [13 31 35]]

Произведение матриц B * A
 [[51 62 73]
 [33 45 57]
 [27 33 39]]


#### Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [7]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
E = np.matrix('1 0 0; 0 1 0; 0 0 1')
L = E.dot(A)
R = A.dot(E)
print("Исходная матрица\n", L)
print("\nМатрица, умноженная на единичную матрицу\n", R)

Исходная матрица
 [[3 2 1]
 [4 5 6]
 [1 2 3]]

Матрица, умноженная на единичную матрицу
 [[3 2 1]
 [4 5 6]
 [1 2 3]]


#### Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [9]:
A = np.matrix('3 2 1; 4 5 6; 1 2 3')
E = np.matrix('0 0 0; 0 0 0; 0 0 0')
R = A.dot(E)
print("Исходная матрица\n", A)
print("\nМатрица, умноженная на нулевую матрицу\n", R)

Исходная матрица
 [[3 2 1]
 [4 5 6]
 [1 2 3]]

Матрица, умноженная на нулевую матрицу
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### Свойства определителя матрицы

#### Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [10]:
A = np.matrix('3 -2 1; 4 5 -6; 1 -2 3')
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print("Определитель исходной матрицы\n", det_A)
print("\nОпределитель транспортированной матрицы\n", det_A_t)

Определитель исходной матрицы
 32.0

Определитель транспортированной матрицы
 32.0


#### Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [11]:
A = np.matrix('3 -2 1; 4 5 -6; 0 0 0')
det_A = round(np.linalg.det(A), 3)
print("Исходная матрица\n", A)
print("\nОпределитель матрицы\n", det_A)

Исходная матрица
 [[ 3 -2  1]
 [ 4  5 -6]
 [ 0  0  0]]

Определитель матрицы
 0.0


#### Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [12]:
A = np.matrix('3 -2 1; 4 5 -6; 1 -2 3')
B = np.matrix('4 5 -6; 3 -2 1; 1 -2 3')
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print("Исходная матрица\n", A)
print("\nОпределитель матрицы\n", det_A)
print("Исходная матрица с переставленными строками\n", B)
print("\nОпределитель матрицы\n", det_B)

Исходная матрица
 [[ 3 -2  1]
 [ 4  5 -6]
 [ 1 -2  3]]

Определитель матрицы
 32.0
Исходная матрица с переставленными строками
 [[ 4  5 -6]
 [ 3 -2  1]
 [ 1 -2  3]]

Определитель матрицы
 -32.0


#### Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [13]:
A = np.matrix('3 -2 1; 3 -2 1; 1 -2 3')
det_A = round(np.linalg.det(A), 3)
print("Исходная матрица\n", A)
print("\nОпределитель матрицы\n", det_A)

Исходная матрица
 [[ 3 -2  1]
 [ 3 -2  1]
 [ 1 -2  3]]

Определитель матрицы
 0.0


#### Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [14]:
A = np.matrix('3 -2 1; 4 5 -6; 1 -2 3')
k = 4
B = A.copy()
B[1, :] = k * B[1, :]
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print("Определитель матрицы умноженной на число\n", det_A * k)
print("\nОпределитель матрицы, где все элементы строки умножены на k\n", det_B)

Определитель матрицы умноженной на число
 128.0

Определитель матрицы, где все элементы строки умножены на k
 128.0


#### Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [35]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
round(np.linalg.det(C), 3)
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)
print("Определитель матрицы из элементов суммы двух слагаемых\n", round(np.linalg.det(C), 3))
print("\nСумма определителей двух соответствующих матриц\n", round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3))

Определитель матрицы из элементов суммы двух слагаемых
 -10.0

Сумма определителей двух соответствующих матриц
 -10.0


#### Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [49]:
A = np.matrix('3 -2 1; 4 5 -6; 1 -2 3')
k = 4
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print("Определитель исходной матрица\n", round(np.linalg.det(A), 3))
print("\nОпределитель матрицы, у которой к элементам одной строки прибавлены элементы другой строки, \
умноженные на одно и тоже число\n", round(np.linalg.det(B), 3))

Определитель исходной матрица
 32.0

Определитель матрицы, у которой к элементам одной строки прибавлены элементы другой строки, умноженные на одно и тоже число
 32.0


#### Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [50]:
A = np.matrix('3 -2 1; 4 5 -6; 1 -2 3')
k = 2
A[1, :] = A[0, :] + k * A[2, :]

print("Определитель полученной матрицы", round(np.linalg.det(A), 3))

Определитель полученной матрицы -0.0


#### Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [52]:
k = 2
A[1, :] = k * A[0, :]
print("Определитель, полученной матрицы\n",round(np.linalg.det(A), 3))

Определитель, полученной матрицы
 0.0


### Обратная матрица

#### Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [54]:
A = np.matrix('2. -1.; 4. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print("Исходная матрица\n", A)
print("\nОбратная матрица от обратной матрицы\n", A_inv_inv)

Исходная матрица
 [[ 2. -1.]
 [ 4.  5.]]

Обратная матрица от обратной матрицы
 [[ 2. -1.]
 [ 4.  5.]]


#### Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [55]:
A = np.matrix('2. -1.; 4. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print("Обратная матрица транспонированной матрицы\n", L)
print("\nТранспонированная матрица от обратной матрицы\n", R)

Обратная матрица транспонированной матрицы
 [[ 0.35714286 -0.28571429]
 [ 0.07142857  0.14285714]]

Транспонированная матрица от обратной матрицы
 [[ 0.35714286 -0.28571429]
 [ 0.07142857  0.14285714]]


#### Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [56]:
A = np.matrix('2. -1.; 4. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print("Обратная матрица произведения матриц\n", L)
print("\nПроизведение обратных матриц\n", R)

Обратная матрица произведения матриц
 [[ 0.09142857 -0.00571429]
 [-0.04714286  0.01857143]]

Произведение обратных матриц
 [[ 0.09142857 -0.00571429]
 [-0.04714286  0.01857143]]
