# Создать ноутбук, в котором будут приведены собственные примеры решения систем линейных уравнений матричным методом и методом Крамера. 

### Метод Крамера

In [5]:
import numpy as np

Создадим и заполним матрицу рандомными значениями от 0 до 10

In [6]:
matrix = np.random.randint (0, 10, (4, 4))
print(matrix)

[[0 8 5 9]
 [3 6 5 9]
 [9 2 9 5]
 [9 9 4 8]]


Найдём определитель

In [11]:
opred_1 = np.linalg.det(matrix)
print(opred_1)

1368.000000000001


Заполним рандомными значенями столбец свободных членов

In [13]:
sv = np.random.randint (0, 10, (4, 1))
print(sv)
x = np.ones((4, 1))

[[4]
 [5]
 [9]
 [5]]


Решим матрицу методом Крамера. Скопируем значения в дополнительную матрицу и подставим в неё столбец свободных членов. Затем найдём определителиь

In [23]:
t = [0, 1, 2, 3]
if opred_1 != 0:
    for i in t:
        mat_dop = matrix.copy()
        mat_dop[:, i] = sv[:, 0]
        x[i,0] = np.linalg.det(mat_dop) / opred_1
    print(x)
else:
    print("Невозможно решить")

[[-0.37214363]
 [ 1.40152339]
 [ 1.95429815]
 [ 0.30903156]]


### Матричный метод:

Пусть дана система $n$ линейных уравнений с $n$ переменными $(n \times n)$.<br> Если основная матрица не вырождена, т.е. $\vert A \vert \ne 0$, тогда для матрицы $А$ существует $А^{-1}$. Умножив матричное уравнение на $А^{-1}$ получим: $$X = А^{-1} * B$$

Создадим и заполним матрицу:

In [24]:
matrix = np.random.randint (0, 10, (4, 4))
print(matrix)

[[7 6 9 1]
 [0 8 6 5]
 [6 0 6 7]
 [6 4 5 8]]


Найдём обратную матрицу

In [25]:
mat_inv = np.linalg.inv(matrix)
print(mat_inv)

[[ 0.07933194 -0.15970772 -0.1263048   0.20041754]
 [ 0.03444676  0.01617954 -0.20615866  0.16597077]
 [ 0.03757829  0.1085595   0.22964509 -0.27348643]
 [-0.10020877  0.04384134  0.05427975  0.06263048]]


Найдём определитель

In [26]:
opred_1 = np.linalg.det(matrix)
print(opred_1)

1915.9999999999998


Заполним столбец свободных членов

In [27]:
sv = np.random.randint (0, 20, (4, 1))
print(sv)

[[ 6]
 [ 1]
 [17]
 [ 4]]


Найдём решения СЛАУ, умножив нашу обратную матрицу на столбец свободных членов:

In [28]:
if opred_1 != 0:
    x = mat_inv.dot(sv)
    print(x)
else: 
    print("Невозможно решить")

[[-1.02922756]
 [-2.61795407]
 [ 3.1440501 ]
 [ 0.61586639]]
